name = "ConstructiveGeometry"
uuid = "d7b4f48a-cc68-4606-be83-5982dfebca4b"
authors = ["Jerome Plut <jerome@fugue.cf> and contributors"]
version = "0.2.0"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
Clipper = "c8f6d549-b3ab-5508-a0d1-48fe138e8cc1"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
FastClosures = "9aa1b823-49e4-5ca5-8b0f-3971ec8bab6a"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
FixedPointNumbers = "53c48c17-4a7d-5ca2-90c5-79b7896eea93"
GLPK = "60bf3e95-4087-53dc-ae20-288a0d20c6a6"
HypergeometricFunctions = "34004b35-14d8-5ef3-9330-4cdb6864b03a"
IGLWrap_jll = "283677c1-8365-580c-84e5-ef4b5d190868"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Polyhedra = "67491407-f73d-577b-9b50-8179a7c68029"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Triangulate = "f7e6ffb2-c36d-4f8f-a77e-16e897189344"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
AbstractTrees = "0.3, 0.4"
Clipper = "0.6"
Colors = "0.12"
DataStructures = "0.17, 0.18"
FastClosures = "0.3"
FileIO = "1.11"
FixedPointNumbers = "0.8"
GLPK = "0.14, 1"
HypergeometricFunctions = "0.3.8"
IGLWrap_jll = "0.1.3"
Makie = "0.14, 0.17"
Polyhedra = "0.6, 0.7"
Rotations = "1.0.4"
StaticArrays = "1"
Triangulate = "2"
Unitful = "1.9"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
